import os
import re
from html import unescape

dirs = [
    ('Arcade', 'arcade', 'Interactive games & simulations'),
    ('Tower Defense', 'tower-def', 'AI-generated tower defense variants from multiple models'),
    ('Rail Shooter', 'rail-shooter', 'AI-generated on-rails action variants'),
    ('SVG Forest', 'svg-forest', 'Explorable SVG art worlds generated by different AI models'),
    ('Depths', 'depths', 'Spinners, trackers & curiosities'),
    ('Utils', 'utils', 'Infographics, visualizers & data tools'),
    ('Learn', 'learn', 'Tutorials, trainers & explainers'),
    ('Vector Defense', 'vector-defense', 'Retro missile command with terrain mechanics')
]

lines = []
lines.append('# Fun with AI\n')
lines.append('A collection of games, tools, and experiments built with AI — hosted on GitHub Pages.\n')
lines.append('## Directory Index & Pages\n')

for section_name, dir_path, section_desc in dirs:
    index_file = os.path.join(dir_path, 'index.html')
    if not os.path.exists(index_file):
        continue
    with open(index_file, 'r', encoding='utf-8') as f:
        html = f.read()
    
    lines.append(f'### [{section_name}]({dir_path}/)\n')
    if section_desc:
        lines.append(f'*{section_desc}*\n')
    
    cards = re.findall(r'<a\s+[^>]*href=[\"\']([^\"\']+)[\"\'][^>]*>(.*?)</a>', html, re.DOTALL | re.IGNORECASE)
    
    for href, content in cards:
        if href.startswith('../') or href.startswith('http') or href.startswith('#') or href == 'index.html':
            continue
        
        tag_open_match = re.search(r'<a\s+[^>]*href=[\"\']' + re.escape(href) + r'[\"\']([^>]*)>', html, re.IGNORECASE)
        data_attrs = tag_open_match.group(1) if tag_open_match else ''
        
        model_attr = re.search(r'data-model=[\"\']([^\"\']+)[\"\']', data_attrs)
        effort_attr = re.search(r'data-effort=[\"\']([^\"\']+)[\"\']', data_attrs)
        
        model_name = ''
        if model_attr:
            model_name = model_attr.group(1)
            if effort_attr and effort_attr.group(1):
                model_name += f' {effort_attr.group(1)}'
        else:
            model_span = re.search(r'class=[\"\'][^\"\']*(?:model-name|model-tag|tile-tag|card-tag)[^\"\']*[\"\'][^>]*>(.*?)</(?:span|div)>', content, re.DOTALL | re.IGNORECASE)
            if model_span:
                model_name = re.sub(r'<[^>]+>', '', model_span.group(1)).strip()
        
        title_match = re.search(r'<(?:h[1-6]|span)[^>]*class=[\"\'][^\"\']*(?:title)[^\"\']*[\"\'][^>]*>(.*?)</(?:h[1-6]|span)>', content, re.DOTALL | re.IGNORECASE)
        if not title_match:
            title_match = re.search(r'<h2>(.*?)</h2>', content, re.DOTALL | re.IGNORECASE)
            
        desc_match = re.search(r'<(?:p|span)[^>]*class=[\"\'][^\"\']*(?:desc|description)[^\"\']*[\"\'][^>]*>(.*?)</(?:p|span)>', content, re.DOTALL | re.IGNORECASE)
        if not desc_match:
            desc_match = re.search(r'<p>(.*?)</p>', content, re.DOTALL | re.IGNORECASE)
            
        title = title_match.group(1) if title_match else ''
        desc = desc_match.group(1) if desc_match else ''
        
        title = unescape(re.sub(r'<[^>]+>', '', title)).strip()
        desc = unescape(re.sub(r'<[^>]+>', '', desc)).strip()
        
        if not title or title == 'Play Now':
            clean_all = unescape(re.sub(r'<[^>]+>', ' ', content)).strip()
            title = ' '.join(clean_all.split())
            if title == 'Play Now' and dir_path == 'vector-defense':
                title = 'Vector Defense'
                desc = 'Retro tactical missile command game with a CRT military aesthetic'
        
        full_href = f'{dir_path}/{href}'
        
        line = f'- **[{title}]({full_href})**'
        if desc:
            line += f' — {desc}'
        if model_name:
            line += f' (*{model_name}*)'
        lines.append(line)
    lines.append('')

lines.append('## Deploy on GitHub Pages\n')
lines.append('1. Push to a public repo.')
lines.append('2. In **Settings → Pages**, set **Source** to "Deploy from a branch", pick `main` and `/ (root)`.')
lines.append('3. Site appears at `https://<user>.github.io/<repo>/`.\n')
lines.append('No build step needed — all static HTML.\n')
lines.append('---\n*Note: This repository is a living collection and is frequently updated.*')

content_out = '\n'.join(lines) + '\n'

with open('README.md', 'w', encoding='utf-8') as f:
    f.write(content_out)

print('README.md generated successfully.')
